name: "Manual dispatch of workflow run"
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: false
        type: string
      greeting:
        description: 'Type of greeting'
        required: false
        type: string
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: 'Display greeting'
        run: echo "${{inputs.greeting}}, ${{inputs.name}}!"