name: Workflow Commands
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "MY_VAL=used in job 2" >> $GITHUB_ENV
#      - name: step-2
#        run: echo $MY_VAL
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo $MY_VAL